### ISSUE TITLE
Lindsey needs a Bio in "Who We Are"

### ISSUE THREAD

**Issue by mauracarter** [idea-analytics/r_and_a_manual#222]
Lindsey needs to add her Bio to this section, as our newest team memeber. :-)

https://github.com/idea-analytics/r_and_a_manual/blob/cbc9c53415dd0e8507080196a4e0b83bc6076598/02-Who_We_Are.Rmd#L75-L76

**Comment by lsmith700** [comment]
Both Lindsey and Karina need to add bios #223

**Comment by lsmith700** [comment]
added bio in "Ch2 add bio, grammatical edits" branch
